name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: registry.lameduse.fr
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-npm-package:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        registry:
          - url: "https://npm.lameduse.fr"
            auth-token-secret: LAMEDUSE_NPM_HOSTED_REGISTRY_PASSWORD
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node environment (for publishing)
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: ${{ matrix.registry.url }}
          scope: "@lameduse"

      - name: Publish package
        run: |
          yarn && yarn rollup || exit 1
          DATE=$(date +%Y%m%d%H%M%S)
          publish=(yarn publish --access=public --no-git-tag-version --non-interactive)
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            publish+=(--tag latest)
          else
            publish+=(--prerelease --preid next.$DATE --tag next)
          fi
          echo "🚀 Publishing npm package with following command line: ${publish[@]}"
          "${publish[@]}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.auth-token-secret] }}

  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.LAMEDUSE_REGISTRY_USERNAME }}
          password: ${{ secrets.LAMEDUSE_REGISTRY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
